# Model Training v5 — Single-Token (a_n), Tree-Native Pipeline

In [1]:
import sys
import json
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer, OneHotEncoder, LabelEncoder
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_class_weight
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

sys.path.append('..')
from src.features import FeatureOptions, load_feature_tables
from src.sanity_check import run_all as sanity_check

In [2]:
# Reproducibility & Config
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# Clinical gold standard: sustained vowel 'A' at normal pitch.
# Isolate to a single token first to prove multifractal features work
# before integrating other vowels/tokens.
SELECTED_TOKEN = 'a_n'
MIN_SAMPLES_PER_CLASS = 50
MAX_SAMPLES_PER_CLASS = 500

# Downsample healthy to match total pathological count (no upsampling/duplication).
# Tree models also handle residual imbalance via class_weight='balanced'.
BALANCE_HEALTHY = True

# Data quality guards
# Keep overlap filter OFF by default: it removes a large portion of pathological signal.
EXCLUDE_OVERLAP_SPEAKERS = False
EXCLUDE_MIXED_BINARY_SPEAKERS = True

N_SPLITS = 5
THRESHOLD_GRID = np.linspace(0.35, 0.65, 11)

# Optimize for what you care about most
BINARY_THRESHOLD_OBJECTIVE = 'accuracy'  # 'accuracy' | 'balanced_accuracy'

TARGET_SOURCE_COL_PREFERENCE = 'pathology_de'
USE_GROUPED_TARGET = True
KEEP_UNMAPPED_LABELS = True
UNMAPPED_LABEL = 'Other'

DISEASE_GROUP_MAP = {
    'Morbus Parkinson': 'Neurological',
    'Rekurrensparese': 'Neurological',
    'Spasmodische Dysphonie': 'Neurological',
    'Phonationsknötchen': 'Structural',
    'Stimmlippenpolyp': 'Structural',
    'Reinke Ödem': 'Structural',
    'Laryngitis': 'Structural',
    'Hypotone Dysphonie': 'Functional',
    'Hyperfunktionelle Dysphonie': 'Functional',
    'Psychogene Dysphonie': 'Functional',
    'Funktionelle Dysphonie': 'Functional',
    'Phonationsknötchen': 'Structural',
    'Reinke Ödem': 'Structural',
}

opts = FeatureOptions(
    prefix=Path('..'),
    include_splits=True,
    random_seed=RANDOM_SEED,
    max_samples_per_class=MAX_SAMPLES_PER_CLASS,
    balance_healthy=BALANCE_HEALTHY,
    selected_token=SELECTED_TOKEN,
    num_workers=None,
)
opts

FeatureOptions(prefix=WindowsPath('..'), input_manifest=WindowsPath('data/processed/manifests/dataset_manifest.csv'), output_core=WindowsPath('data/processed/features/sample_core.csv'), output_acoustic=WindowsPath('data/processed/features/acoustic_features.csv'), output_multifractal=WindowsPath('data/processed/features/multifractal_features.csv'), output_opensmile=WindowsPath('data/processed/features/opensmile_features.csv'), output_splits=WindowsPath('data/processed/features/sample_splits.csv'), output_summary_json=WindowsPath('data/processed/features/feature_summary.json'), include_splits=True, train_ratio=0.7, val_ratio=0.15, test_ratio=0.15, random_seed=42, num_workers=None, max_samples_per_class=500, balance_healthy=True, normalize_audio=True, target_sample_rate=22050, selected_token='a_n', mfdfa_order=1, mfdfa_q_min=-5.0, mfdfa_q_max=5.0, mfdfa_q_step=1.0, mfdfa_num_scales=20)

In [3]:
# Load Features (Sample Level) with config-safety check
build_cfg_path = Path('..') / 'data' / 'processed' / 'features' / 'feature_build_config.json'
desired_cfg = {
    'max_samples_per_class': MAX_SAMPLES_PER_CLASS,
    'balance_healthy': BALANCE_HEALTHY,
    'target_sample_rate': opts.target_sample_rate,
    'selected_token': SELECTED_TOKEN,
}

force_rebuild = False
if build_cfg_path.exists():
    saved_cfg = json.loads(build_cfg_path.read_text(encoding='utf-8'))
    mismatches = {
        k: (saved_cfg.get(k), v)
        for k, v in desired_cfg.items()
        if saved_cfg.get(k) != v
    }
    if mismatches:
        force_rebuild = True
        print('Config mismatch vs cached features -> forcing rebuild:')
        for k, (old_v, new_v) in mismatches.items():
            print(f'  {k}: cached={old_v} -> desired={new_v}')

if force_rebuild:
    feature_dir = Path('..') / 'data' / 'processed' / 'features'
    for p in [
        feature_dir / 'sample_core.csv',
        feature_dir / 'acoustic_features.csv',
        feature_dir / 'multifractal_features.csv',
        feature_dir / 'opensmile_features.csv',
        feature_dir / 'sample_splits.csv',
        feature_dir / 'feature_summary.json',
        feature_dir / 'feature_build_config.json',
    ]:
        if p.exists():
            p.unlink()
    print('Deleted stale cached feature artifacts. Rebuilding now...')

tables = load_feature_tables(options=opts, build_if_missing=True, save_if_built=True)

# Deduplicate each table on sample_key before merging to prevent
# cartesian explosion if upstream pipeline produces duplicate keys.
core_df = tables['core'].drop_duplicates(subset=['sample_key']).copy()
acoustic_df = tables['acoustic'].drop_duplicates(subset=['sample_key']).copy()
multifractal_df = tables['multifractal'].drop_duplicates(subset=['sample_key']).copy()
opensmile_df = tables.get('opensmile', pd.DataFrame()).drop_duplicates(subset=['sample_key']).copy() if 'opensmile' in tables and not tables.get('opensmile', pd.DataFrame()).empty else pd.DataFrame()
splits_df = tables.get('splits', pd.DataFrame()).drop_duplicates(subset=['sample_key']).copy() if 'splits' in tables and not tables.get('splits', pd.DataFrame()).empty else pd.DataFrame()

df = core_df.merge(acoustic_df, on='sample_key', how='left')
df = df.merge(multifractal_df, on='sample_key', how='left')
if not opensmile_df.empty:
    df = df.merge(opensmile_df, on='sample_key', how='left')
if not splits_df.empty:
    df = df.merge(splits_df, on='sample_key', how='left')

if 'feature_status' in df.columns:
    df = df[df['feature_status'].isin(['ok', 'partial_failure'])].copy()
if 'acoustic_status' in df.columns:
    df = df[df['acoustic_status'] == 'ok'].copy()
if 'mf_status' in df.columns:
    df = df[df['mf_status'] == 'ok'].copy()
if 'opensmile_status' in df.columns:
    df = df[df['opensmile_status'] == 'ok'].copy()

print('Merged sample-level shape:', df.shape)
print('Unique speakers:', df['speaker_id'].nunique())

Pathologies:   0%|          | 0/12 [00:00<?, ?pathology/s]

Funktionelle Dysphonie recordings:   0%|          | 0/112 [00:00<?, ?recording/s]

Funktionelle Dysphonie/350 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/351 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/631 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/634 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/718 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/722 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/723 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/727 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/729 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/730 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/851 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/870 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/878 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/913 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1193 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1200 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1230 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1240 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1241 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1244 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1254 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1258 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1281 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1309 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1318 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1322 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1326 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1328 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1400 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1415 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1432 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1435 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1441 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1552 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1589 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1609 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1611 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1627 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1640 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1642 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1645 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1659 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1680 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1681 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1685 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1688 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1694 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1742 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1798 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1801 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1824 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1827 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1862 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1899 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1935 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1936 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1958 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1966 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/1977 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2006 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2112 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2123 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2231 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2265 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2267 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2290 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2297 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2302 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2303 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2308 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2310 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2312 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2313 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2314 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2318 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2327 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2336 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2340 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2357 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2359 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2360 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2365 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2367 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2382 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2410 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2413 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2416 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2417 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2419 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2427 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2429 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2431 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2432 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2442 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2444 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2445 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2446 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2448 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2457 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2459 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2477 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2481 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2483 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2497 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2499 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2502 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2504 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2505 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2506 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2524 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2528 files:   0%|          | 0/14 [00:00<?, ?file/s]

Funktionelle Dysphonie/2601 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy recordings:   0%|          | 0/687 [00:00<?, ?recording/s]

healthy/1 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/3 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/4 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/5 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/6 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/7 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/8 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/9 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/10 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/11 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/12 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/13 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/14 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/15 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/16 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/17 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/18 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/19 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/20 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/21 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/22 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/23 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/24 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/25 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/26 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/27 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/28 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/29 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/30 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/31 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/32 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/33 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/34 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/35 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/36 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/37 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/38 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/39 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/40 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/41 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/42 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/43 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/44 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/45 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/46 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/47 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/48 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/49 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/50 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/52 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/53 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/54 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/55 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/56 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/57 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/58 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/59 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/60 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/61 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/62 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/63 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/64 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/65 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/66 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/67 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/68 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/69 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/70 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/71 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/72 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/74 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/77 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/78 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/79 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/80 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/81 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/82 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/83 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/84 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/85 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/86 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/87 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/88 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/89 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/90 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/91 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/92 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/93 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/94 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/95 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/96 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/97 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/98 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/99 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/100 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/102 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/103 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/104 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/112 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/113 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/114 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/115 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/116 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/117 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/121 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/122 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/123 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/124 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/125 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/126 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/132 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/133 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/134 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/135 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/136 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/137 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/145 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/153 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/156 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/157 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/158 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/675 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/676 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/677 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/678 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/679 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/680 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/681 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/682 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/683 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/684 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/685 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/686 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/687 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/688 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/689 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/690 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/691 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/694 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/695 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/696 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/697 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/698 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/699 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/700 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/701 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/702 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/703 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/704 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/705 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/706 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/707 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/708 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/709 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/710 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/711 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/732 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/733 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/734 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/735 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/736 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/737 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/738 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/739 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/740 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/743 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/744 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/745 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/746 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/747 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/782 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/803 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/804 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/805 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/806 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/807 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/808 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/809 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/810 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/811 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/812 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/813 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/831 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/832 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/833 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/834 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/835 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/836 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/837 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/838 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/839 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/840 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/841 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/842 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/843 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/852 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/860 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/861 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/862 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/865 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/867 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/941 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/942 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/943 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/944 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/945 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/946 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/947 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/948 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/949 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/950 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/951 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/952 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/953 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/954 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/955 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/956 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/957 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/958 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/959 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/960 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/961 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/962 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/963 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/964 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/965 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/967 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/968 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/969 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/970 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/971 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/972 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/973 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/974 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/975 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/976 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/977 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/978 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/979 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/980 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/981 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/982 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/983 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/984 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/985 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/986 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/987 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/988 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/989 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/990 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/991 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/992 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/993 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/994 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/995 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/996 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/997 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/998 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/999 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1000 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1002 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1003 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1004 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1005 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1006 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1007 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1008 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1009 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1010 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1011 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1012 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1013 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1014 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1015 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1016 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1017 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1018 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1019 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1020 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1021 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1022 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1023 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1024 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1025 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1026 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1027 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1028 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1029 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1030 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1031 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1032 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1033 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1034 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1035 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1036 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1059 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1060 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1061 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1062 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1063 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1064 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1065 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1066 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1067 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1068 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1069 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1070 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1071 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1072 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1073 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1074 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1075 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1076 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1077 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1078 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1079 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1080 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1081 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1082 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1091 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1092 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1093 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1094 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1095 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1096 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1097 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1098 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1099 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1100 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1101 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1102 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1103 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1104 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1105 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1106 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1107 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1108 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1109 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1110 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1111 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1112 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1121 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1122 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1123 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1124 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1125 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1126 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1127 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1128 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1129 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1130 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1131 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1132 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1133 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1134 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1135 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1136 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1137 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1138 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1139 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1140 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1141 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1142 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1143 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1144 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1145 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1146 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1147 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1148 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1149 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1150 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1151 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1153 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1155 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1167 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1168 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1169 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1170 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1171 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1172 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1173 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1174 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1175 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1176 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1177 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1178 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1179 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1180 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1181 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1182 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1183 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1184 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1185 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1207 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1208 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1209 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1210 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1211 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1212 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1214 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1215 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1216 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1278 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1308 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1320 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1336 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1342 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1343 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1344 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1345 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1346 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1347 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1348 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1349 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1350 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1351 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1352 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1353 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1354 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1355 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1356 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1357 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1358 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1359 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1360 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1361 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1362 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1363 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1364 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1365 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1366 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1367 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1368 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1369 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1370 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1371 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1372 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1373 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1374 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1375 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1377 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1427 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1460 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1504 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1505 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1506 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1507 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1508 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1509 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1510 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1511 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1512 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1513 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1514 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1515 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1516 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1517 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1518 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1519 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1520 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1521 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1522 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1523 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1524 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1526 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1527 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1528 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1529 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1530 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1531 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1532 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1533 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1534 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1535 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1536 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1537 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1538 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1539 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1540 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1541 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1542 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1543 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1544 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1573 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1577 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1579 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1582 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1583 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1584 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1585 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1586 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1587 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1598 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1605 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1612 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1623 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1695 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1696 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1697 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1698 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1699 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1700 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1701 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1702 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1703 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1704 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1705 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1706 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1707 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1708 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1709 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1710 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1711 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1712 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1724 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1725 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1726 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1727 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1728 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1729 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1730 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1731 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1732 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1733 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1734 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1735 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1736 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1737 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1738 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1739 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1740 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1775 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1815 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1837 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1838 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1839 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1840 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1841 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1842 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1843 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1844 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1845 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1846 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1847 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1848 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1849 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1850 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1851 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1852 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1853 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1854 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1855 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1856 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1857 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1858 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1859 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1860 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1865 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1870 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1871 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1872 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1873 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1874 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1875 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1876 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1877 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1878 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1879 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1880 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1881 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1882 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1883 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1884 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1885 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1886 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1915 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1916 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1917 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1918 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1919 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1920 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1921 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1922 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1923 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1924 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1925 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/1926 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/1947 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/1956 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1969 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1974 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/1995 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/1996 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2018 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2036 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2037 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2038 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2039 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2040 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2041 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2042 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2043 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2044 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2045 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2046 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2047 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2048 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2049 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2050 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2051 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2052 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2053 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2054 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2084 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2108 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2142 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2162 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2163 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2164 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2165 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2166 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2167 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2168 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2169 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2170 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2171 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2172 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2173 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2174 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2175 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2176 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2177 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2178 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2179 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2180 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2181 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2195 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2196 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2197 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2198 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2199 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2200 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2201 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2202 files:   0%|          | 0/13 [00:00<?, ?file/s]

healthy/2203 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2204 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2205 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2206 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2207 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2208 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2209 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2210 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2244 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2248 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2249 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2250 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2251 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2252 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2253 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2254 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2255 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2256 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2257 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2258 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2259 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2260 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2261 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2262 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2263 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2264 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2278 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2279 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2280 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2281 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2282 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2283 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2284 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2285 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2286 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2407 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2462 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2478 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2495 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2532 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2561 files:   0%|          | 0/14 [00:00<?, ?file/s]

healthy/2576 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie recordings:   0%|          | 0/213 [00:00<?, ?recording/s]

Hyperfunktionelle Dysphonie/106 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/127 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/140 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/144 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/159 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/160 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/348 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/355 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/363 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/499 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/665 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/669 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/692 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/724 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/819 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/827 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/829 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/850 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/854 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/857 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/868 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/881 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/888 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/889 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/890 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/894 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/898 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/909 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/922 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/934 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1037 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1043 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1044 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1050 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1051 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1083 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1085 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1088 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1090 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1113 files:   0%|          | 0/13 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1118 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1189 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1196 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1204 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1222 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1266 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1280 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1282 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1284 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1285 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1294 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1299 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1310 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1324 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1327 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1331 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1335 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1379 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1380 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1394 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1406 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1431 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1442 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1443 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1459 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1462 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1464 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1468 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1471 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1476 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1492 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1500 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1562 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1566 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1569 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1571 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1591 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1594 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1602 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1607 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1608 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1637 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1643 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1648 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1653 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1660 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1669 files:   0%|          | 0/13 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1682 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1686 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1690 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1741 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1745 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1753 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1754 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1758 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1777 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1778 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1786 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1792 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1794 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1800 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1802 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1812 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1813 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1816 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1822 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1823 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1861 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1887 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1888 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1891 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1895 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1898 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1900 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1903 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1906 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1910 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1927 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1929 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1934 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1944 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1952 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1964 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1976 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1978 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1982 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1983 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1988 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1989 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1990 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/1993 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2012 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2034 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2062 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2067 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2071 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2077 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2080 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2081 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2090 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2102 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2104 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2105 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2107 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2114 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2121 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2122 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2124 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2135 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2138 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2139 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2151 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2184 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2185 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2186 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2215 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2221 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2224 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2225 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2228 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2229 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2230 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2232 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2233 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2239 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2240 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2241 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2245 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2270 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2272 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2288 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2292 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2293 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2298 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2307 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2317 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2331 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2338 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2363 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2370 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2374 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2378 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2398 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2399 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2420 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2425 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2438 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2447 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2449 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2454 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2463 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2466 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2471 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2479 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2480 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2482 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2487 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2492 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2517 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2521 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2523 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2526 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2540 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2545 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2546 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2553 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2572 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2577 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2589 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2590 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2591 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2603 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hyperfunktionelle Dysphonie/2604 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hypotone Dysphonie recordings:   0%|          | 0/5 [00:00<?, ?recording/s]

Hypotone Dysphonie/129 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hypotone Dysphonie/1744 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hypotone Dysphonie/2013 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hypotone Dysphonie/2020 files:   0%|          | 0/14 [00:00<?, ?file/s]

Hypotone Dysphonie/2133 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis recordings:   0%|          | 0/140 [00:00<?, ?recording/s]

Laryngitis/107 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/139 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/141 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/493 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/497 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/498 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/563 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/568 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/715 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/818 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/819 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/824 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/828 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/844 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/871 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/884 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/886 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/902 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/904 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/910 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/918 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/919 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/930 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/931 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/935 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1046 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1047 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1119 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1161 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1163 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1188 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1192 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1221 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1228 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1229 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1233 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1235 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1237 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1246 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1248 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1257 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1259 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1260 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1264 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1265 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1269 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1274 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1283 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1295 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1300 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1301 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1307 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1311 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1315 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1388 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1404 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1405 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1414 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1418 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1426 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1436 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1440 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1447 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1456 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1463 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1472 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1554 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1567 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1578 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1591 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1599 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1610 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1613 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1614 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1617 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1629 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1665 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1780 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1783 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1795 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1796 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1806 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1809 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1930 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1940 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1953 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1965 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1973 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1978 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/1987 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2003 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2012 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2021 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2028 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2075 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2079 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2097 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2101 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2110 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2120 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2126 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2128 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2156 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2191 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2219 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2242 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2276 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2296 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2301 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2305 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2315 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2321 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2328 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2351 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2370 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2404 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2424 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2435 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2443 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2487 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2510 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2511 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2514 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2516 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2521 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2525 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2541 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2542 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2555 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2556 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2567 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2574 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2578 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2582 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2585 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2588 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2600 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2602 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2605 files:   0%|          | 0/14 [00:00<?, ?file/s]

Laryngitis/2610 files:   0%|          | 0/14 [00:00<?, ?file/s]

Morbus Parkinson recordings:   0%|          | 0/1 [00:00<?, ?recording/s]

Morbus Parkinson/1580 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen recordings:   0%|          | 0/17 [00:00<?, ?recording/s]

Phonationsknötchen/131 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/870 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/900 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1044 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1285 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1294 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1395 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1464 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1607 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1616 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1643 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1669 files:   0%|          | 0/13 [00:00<?, ?file/s]

Phonationsknötchen/1745 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1800 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1866 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/1927 files:   0%|          | 0/14 [00:00<?, ?file/s]

Phonationsknötchen/2112 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie recordings:   0%|          | 0/91 [00:00<?, ?recording/s]

Psychogene Dysphonie/151 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/366 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/741 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/823 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/848 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/877 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/885 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/911 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/917 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1042 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1051 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1053 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1058 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1198 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1225 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1230 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1258 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1266 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1306 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1319 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1322 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1329 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1335 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1337 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1340 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1384 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1400 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1408 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1421 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1425 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1432 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1459 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1477 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1479 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1566 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1568 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1593 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1661 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1663 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1673 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1675 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1690 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1744 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1767 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1787 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1868 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1891 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1900 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1904 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1910 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1928 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1931 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1951 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1958 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1959 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1964 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1988 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/1989 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2025 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2074 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2085 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2104 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2107 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2112 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2123 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2134 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2213 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2246 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2275 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2302 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2310 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2312 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2316 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2317 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2336 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2337 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2339 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2372 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2431 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2433 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2441 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2452 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2489 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2517 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2520 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2526 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2528 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2533 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2534 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2535 files:   0%|          | 0/14 [00:00<?, ?file/s]

Psychogene Dysphonie/2577 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem recordings:   0%|          | 0/68 [00:00<?, ?recording/s]

Reinke Ödem/495 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/564 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/627 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/630 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/632 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/720 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/821 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/886 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/889 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/901 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1045 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1046 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1056 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1090 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1206 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1221 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1229 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1253 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1274 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1382 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1436 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1447 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1453 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1462 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1500 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1563 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1572 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1610 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1656 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1667 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1717 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1721 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1778 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1811 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1828 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1889 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1890 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1941 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1946 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/1963 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2031 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2089 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2098 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2110 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2112 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2118 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2161 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2188 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2193 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2211 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2271 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2305 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2333 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2344 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2345 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2358 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2375 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2381 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2411 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2426 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2449 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2491 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2518 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2573 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2588 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2591 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2594 files:   0%|          | 0/14 [00:00<?, ?file/s]

Reinke Ödem/2595 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese recordings:   0%|          | 0/213 [00:00<?, ?recording/s]

Rekurrensparese/105 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/108 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/120 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/128 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/130 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/138 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/142 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/150 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/152 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/155 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/352 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/356 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/358 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/362 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/364 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/365 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/448 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/450 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/492 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/565 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/627 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/629 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/632 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/633 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/670 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/671 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/712 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/716 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/725 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/726 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/728 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/825 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/849 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/855 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/859 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/864 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/869 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/874 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/879 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/880 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/883 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/887 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/893 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/896 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/897 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/908 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/912 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/914 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/924 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/926 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/928 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/929 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1040 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1049 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1054 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1120 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1166 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1206 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1223 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1249 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1256 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1262 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1263 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1270 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1271 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1272 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1277 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1289 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1292 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1293 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1304 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1314 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1325 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1330 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1382 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1390 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1397 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1399 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1402 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1407 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1418 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1424 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1434 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1437 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1444 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1466 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1470 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1478 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1484 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1489 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1547 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1548 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1549 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1553 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1555 files:   0%|          | 0/11 [00:00<?, ?file/s]

Rekurrensparese/1564 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1570 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1581 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1601 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1604 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1620 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1624 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1626 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1630 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1631 files:   0%|          | 0/8 [00:00<?, ?file/s]

Rekurrensparese/1638 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1641 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1644 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1655 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1658 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1662 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1664 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1671 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1676 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1683 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1691 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1713 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1722 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1743 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1748 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1755 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1760 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1776 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1784 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1785 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1788 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1789 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1803 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1818 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1820 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1825 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1826 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1829 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1830 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1831 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1832 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1835 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1836 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1863 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1867 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1892 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1901 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1939 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1955 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/1970 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2002 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2007 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2009 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2014 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2024 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2033 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2058 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2072 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2073 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2078 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2083 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2086 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2088 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2100 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2109 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2115 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2148 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2150 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2152 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2153 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2155 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2160 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2182 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2190 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2192 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2216 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2218 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2235 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2237 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2243 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2247 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2274 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2330 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2341 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2342 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2346 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2378 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2393 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2394 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2395 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2408 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2414 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2418 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2430 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2450 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2455 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2460 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2464 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2465 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2469 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2476 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2491 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2493 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2496 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2501 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2507 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2508 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2512 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2527 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2536 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2538 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2539 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2562 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2563 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2564 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2565 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2570 files:   0%|          | 0/14 [00:00<?, ?file/s]

Rekurrensparese/2581 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie recordings:   0%|          | 0/64 [00:00<?, ?recording/s]

Spasmodische Dysphonie/143 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/665 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/901 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1438 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1482 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1565 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1652 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1666 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1672 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1677 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1679 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1689 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1723 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1752 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1757 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1762 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1763 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1769 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1770 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1782 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1790 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1797 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1804 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1807 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1817 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1821 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1834 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1869 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1902 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1908 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1909 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1914 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1937 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1938 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1945 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1950 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1960 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1961 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1972 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1992 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1994 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/1998 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2008 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2010 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2022 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2023 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2030 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2082 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2141 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2158 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2159 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2194 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2227 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2234 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2273 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2304 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2320 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2352 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2361 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2396 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2397 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2440 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2485 files:   0%|          | 0/14 [00:00<?, ?file/s]

Spasmodische Dysphonie/2560 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp recordings:   0%|          | 0/45 [00:00<?, ?recording/s]

Stimmlippenpolyp/109 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/131 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/491 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/501 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/504 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/562 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/720 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/859 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/895 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/932 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1052 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1157 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1164 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1188 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1317 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1334 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1386 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1389 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1433 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1525 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1576 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1621 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1622 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1639 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1719 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1722 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1749 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1764 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1779 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1890 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/1957 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2005 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2056 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2090 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2099 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2157 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2300 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2303 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2466 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2518 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2525 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2557 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2572 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2587 files:   0%|          | 0/14 [00:00<?, ?file/s]

Stimmlippenpolyp/2592 files:   0%|          | 0/14 [00:00<?, ?file/s]

Extracting features:   0%|          | 0/1656 [00:00<?, ?sample/s]

Merged sample-level shape: (1656, 212)
Unique speakers: 1355

In [4]:
# Build Targets
raw_target = df[TARGET_SOURCE_COL_PREFERENCE].astype(str).str.strip()
if USE_GROUPED_TARGET:
    mapped_target = raw_target.map(DISEASE_GROUP_MAP)
    mapped_target = mapped_target.fillna(raw_target if KEEP_UNMAPPED_LABELS else UNMAPPED_LABEL)
    df['target_label'] = mapped_target.astype(str)
else:
    df['target_label'] = raw_target

target_col = 'target_label'

# Optional quality guard 1: remove overlap speakers that appear in multiple pathologies
if EXCLUDE_OVERLAP_SPEAKERS:
    overlap_cols = [c for c in ['is_overlap_speaker', 'is_overlap_speaker_id'] if c in df.columns]
    if overlap_cols:
        overlap_mask = pd.Series(False, index=df.index)
        for c in overlap_cols:
            overlap_mask = overlap_mask | df[c].astype(str).str.lower().eq('true')
        removed = int(overlap_mask.sum())
        if removed > 0:
            print(f'Removing overlap-speaker rows: {removed}')
            df = df.loc[~overlap_mask].copy()

# Optional quality guard 2: remove speakers with mixed binary labels (healthy + pathological)
if EXCLUDE_MIXED_BINARY_SPEAKERS and 'speaker_id' in df.columns and 'is_healthy' in df.columns:
    grp = df.groupby(df['speaker_id'].astype(str))['is_healthy'].nunique()
    bad_speakers = set(grp[grp > 1].index.tolist())
    if bad_speakers:
        removed = int(df['speaker_id'].astype(str).isin(bad_speakers).sum())
        print(f'Removing mixed-label speaker rows: {removed} from {len(bad_speakers)} speakers')
        df = df.loc[~df['speaker_id'].astype(str).isin(bad_speakers)].copy()

small_classes = df[target_col].value_counts()[df[target_col].value_counts() < MIN_SAMPLES_PER_CLASS].index.tolist()
if small_classes:
    print(f'Dropping classes with < {MIN_SAMPLES_PER_CLASS} samples: {small_classes}')
    df = df[~df[target_col].isin(small_classes)].copy()

display(df[target_col].value_counts().to_frame('sample_count'))

Removing mixed-label speaker rows: 35 from 16 speakers

              sample_count
target_label
healthy                671
Functional             405
Neurological           277
Structural             268

In [5]:
# Prep Training Matrices
meta_cols = {
    'sample_key', 'duplicate_class_key', 'recording_id', 'speaker_id', 'wav_path',
    'feature_status', 'feature_error', 'acoustic_status', 'acoustic_error',
    'mf_status', 'mf_error', 'opensmile_status', 'opensmile_error',
    'split', 'split_seed', 'pathology_de', 'pathology_en', target_col, 'is_healthy',
}

numeric_cols = [c for c in df.columns if c not in meta_cols and pd.api.types.is_numeric_dtype(df[c])]

# Only include 'token' as a categorical feature when training on multiple tokens.
# With a single token (e.g. a_n), it's a constant column and adds no information.
categorical_cols = []
if 'sex' in df.columns:
    categorical_cols.append('sex')
if 'token' in df.columns and SELECTED_TOKEN is None:
    categorical_cols.append('token')

X = df[numeric_cols + categorical_cols].copy()
# Binary classification: 1=Healthy, 0=Pathological
y_bin = df['is_healthy'].astype(int).copy()
y_multi = df[target_col].astype(str).copy()
groups = df['speaker_id'].astype(str).copy()
tokens = df['token'].astype(str).copy() if 'token' in df.columns else pd.Series(['__missing__'] * len(df), index=df.index)

print('Total tokens/samples:', len(df))
print('Features per sample:', len(numeric_cols))
print('Categorical columns:', categorical_cols)
print('Unique tokens:', tokens.nunique())

Total tokens/samples: 1621
Features per sample: 191
Categorical columns: ['sex']
Unique tokens: 1

In [6]:
# Sanity Check — display diagnostics before training
sanity_check(df, tables, opts, numeric_cols, categorical_cols, target_col=target_col)

────────────────────────────────────────────────────────────
  Build Configuration
────────────────────────────────────────────────────────────
  selected_token                  a_n
  target_sample_rate              22050
  max_samples_per_class           500
  balance_healthy                 True
  normalize_audio                 True
  mfdfa_order                     1
  mfdfa_q_range                   [-5.0, 5.0] step 1.0
  mfdfa_num_scales                20
  random_seed                     42

────────────────────────────────────────────────────────────
  Data Overview
────────────────────────────────────────────────────────────
Total samples (rows):  1621
Total columns:         213
Unique speakers:       1339
Unique tokens:         1  →  ['a_n']
Sex distribution:      {'w': 1050, 'm': 571}

────────────────────────────────────────────────────────────
  Class Distribution
────────────────────────────────────────────────────────────
  healthy                         671 (41.4%)
  Functional                      405 (25.0%)
  Neurological                    277 (17.1%)
  Structural                      268 (16.5%)

  Binary balance → Healthy: 671  |  Pathological: 950  |  ratio: 0.71

────────────────────────────────────────────────────────────
  Audio Properties
────────────────────────────────────────────────────────────
Sample rate:  22050 Hz  (uniform ✓)
Duration (s): mean=1.29  std=0.45  min=0.39  max=4.39
Num samples:  mean=28372  min=8673  max=96800

────────────────────────────────────────────────────────────
  Feature Extraction Status
────────────────────────────────────────────────────────────
  core             1656 rows  →  {'ok': 1656}
  acoustic         1656 rows  →  {'ok': 1656}
  multifractal     1656 rows  →  {'ok': 1656}
  opensmile        1656 rows  →  {'ok': 1656}

────────────────────────────────────────────────────────────
  Feature Summary
────────────────────────────────────────────────────────────
Total numeric features: 191
Categorical features:   ['sex']

  Group         Count  Example columns
  ────────────  ─────  ────────────────────────────────────────
  ac               84  ac_time_energy, ac_time_abs_mean, ac_time_peak, … (81 more)
  audio             3  audio_sample_rate, audio_num_samples, audio_duration_seconds
  is                2  is_overlap_speaker, is_overlap_speaker_id
  mf               14  mf_hq_mean, mf_hq_std, mf_hq_min, … (11 more)
  os               88  os_F0semitoneFrom27.5Hz_sma3nz_amean, os_F0semitoneFrom27.5Hz_sma3nz_stddevNorm, os_F0semitoneFrom27.5Hz_sma3nz_percentile20.0, … (85 more)

────────────────────────────────────────────────────────────
  Missing Values (NaN)
────────────────────────────────────────────────────────────
Features with any NaN:  0 / 191

In [10]:
# Preprocessing Pipeline
#
# KEY CHANGES (per reviewer feedback):
# 1. Tree models (XGBoost, LightGBM, RF) get NO imputation and NO scaling.
#    They handle NaN natively — "missing pitch" is itself a signal of pathology.
#    Imputing with 0 + Yeo-Johnson warps that into a huge negative outlier that
#    destroys the tree's ability to learn "missing = severe pathology".
# 2. Linear models (LogReg) still get imputation + scaling (they require it).
# 3. No feature selection step at all — with ~191 features, tree models handle
#    them natively. Linear selectors (LinearSVC L1, ANOVA) were discarding the
#    best multifractal features because they can't see non-linear structure.

TREE_MODELS = (RandomForestClassifier, XGBClassifier, LGBMClassifier)

# Tree-friendly: pass numerics through as-is (NaN preserved), one-hot categoricals
tree_preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numeric_cols),
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), categorical_cols),
    ] if categorical_cols else [
        ('num', 'passthrough', numeric_cols),
    ],
    remainder='drop',
).set_output(transform='pandas')

# Linear-model preprocessor: imputation + scaling required
linear_preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='constant', fill_value=0.0, add_indicator=True)),
            ('scaler', PowerTransformer(method='yeo-johnson', standardize=True)),
            ('variance', VarianceThreshold(threshold=0.0)),
        ]), numeric_cols),
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), categorical_cols),
    ] if categorical_cols else [
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='constant', fill_value=0.0, add_indicator=True)),
            ('scaler', PowerTransformer(method='yeo-johnson', standardize=True)),
            ('variance', VarianceThreshold(threshold=0.0)),
        ]), numeric_cols),
    ],
    remainder='drop',
).set_output(transform='pandas')

def make_pipe(model):
    """Build pipeline: auto-selects tree vs linear preprocessor, no feature selection."""
    prep = tree_preprocessor if isinstance(model, TREE_MODELS) else linear_preprocessor
    return Pipeline(steps=[
        ('prep', prep),
        ('model', model),
    ])

In [11]:
def _make_sample_weights(y_enc):
    classes = np.unique(y_enc)
    weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_enc)
    weight_map = {cls: w for cls, w in zip(classes, weights)}
    return np.array([weight_map[v] for v in y_enc], dtype=float)


def evaluate_binary_sample_cv(model, X, y, groups, n_splits=5):
    cv = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_SEED)
    
    fold_rows = []
    for fold, (tr, te) in enumerate(cv.split(X, y, groups), start=1):
        X_tr, X_te = X.iloc[tr], X.iloc[te]
        y_tr, y_te = y.iloc[tr], y.iloc[te]

        pipe = make_pipe(clone(model))
        pipe.fit(X_tr, y_tr)
        
        # Fast threshold tuning on train probas (objective configurable)
        p_tr = pipe.predict_proba(X_tr)[:, 1]
        best_thr, best_score = 0.5, -1.0
        for thr in THRESHOLD_GRID:
            pred_tr = (p_tr >= thr).astype(int)
            if BINARY_THRESHOLD_OBJECTIVE == 'accuracy':
                score = accuracy_score(y_tr, pred_tr)
            else:
                score = balanced_accuracy_score(y_tr, pred_tr)
            if score > best_score:
                best_score = score
                best_thr = float(thr)

        p_te = pipe.predict_proba(X_te)[:, 1]
        pred_te = (p_te >= best_thr).astype(int)

        fold_rows.append({
            'fold': fold,
            'threshold': best_thr,
            'accuracy': accuracy_score(y_te, pred_te),
            'balanced_accuracy': balanced_accuracy_score(y_te, pred_te),
            'f1_macro': f1_score(y_te, pred_te, average='macro', zero_division=0),
        })
        
    fold_df = pd.DataFrame(fold_rows)
    return fold_df, {
        'accuracy_mean': fold_df['accuracy'].mean(),
        'balanced_accuracy_mean': fold_df['balanced_accuracy'].mean(),
        'f1_macro_mean': fold_df['f1_macro'].mean(),
    }


def evaluate_binary_speaker_cv(model, X, y, groups, n_splits=5):
    """Train on token-level, evaluate on speaker-aggregated probabilities per fold."""
    cv = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_SEED)
    fold_rows = []

    for fold, (tr, te) in enumerate(cv.split(X, y, groups), start=1):
        X_tr, X_te = X.iloc[tr], X.iloc[te]
        y_tr, y_te = y.iloc[tr], y.iloc[te]
        g_tr, g_te = groups.iloc[tr], groups.iloc[te]

        pipe = make_pipe(clone(model))
        pipe.fit(X_tr, y_tr)

        # Tune threshold at speaker level on train split
        p_tr = pipe.predict_proba(X_tr)[:, 1]
        tr_eval = pd.DataFrame({
            'speaker_id': g_tr.astype(str).values,
            'y': y_tr.astype(int).values,
            'p': p_tr,
        })
        tr_spk = tr_eval.groupby('speaker_id', as_index=False).agg(y=('y', 'first'), p=('p', 'mean'))

        best_thr, best_score = 0.5, -1.0
        for thr in THRESHOLD_GRID:
            pred = (tr_spk['p'].values >= thr).astype(int)
            if BINARY_THRESHOLD_OBJECTIVE == 'accuracy':
                score = accuracy_score(tr_spk['y'].values, pred)
            else:
                score = balanced_accuracy_score(tr_spk['y'].values, pred)
            if score > best_score:
                best_score = score
                best_thr = float(thr)

        # Evaluate on speaker-aggregated test predictions
        p_te = pipe.predict_proba(X_te)[:, 1]
        te_eval = pd.DataFrame({
            'speaker_id': g_te.astype(str).values,
            'y': y_te.astype(int).values,
            'p': p_te,
        })
        te_spk = te_eval.groupby('speaker_id', as_index=False).agg(y=('y', 'first'), p=('p', 'mean'))
        pred_spk = (te_spk['p'].values >= best_thr).astype(int)

        fold_rows.append({
            'fold': fold,
            'threshold': best_thr,
            'accuracy': accuracy_score(te_spk['y'].values, pred_spk),
            'balanced_accuracy': balanced_accuracy_score(te_spk['y'].values, pred_spk),
            'f1_macro': f1_score(te_spk['y'].values, pred_spk, average='macro', zero_division=0),
        })

    fold_df = pd.DataFrame(fold_rows)
    return fold_df, {
        'accuracy_mean': fold_df['accuracy'].mean(),
        'balanced_accuracy_mean': fold_df['balanced_accuracy'].mean(),
        'f1_macro_mean': fold_df['f1_macro'].mean(),
    }


def evaluate_multiclass_sample_and_speaker_cv(model, X, y, groups, n_splits=5):
    cv = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_SEED)
    sample_rows, speaker_rows = [], []

    for fold, (tr, te) in enumerate(cv.split(X, y, groups), start=1):
        X_tr, X_te = X.iloc[tr], X.iloc[te]
        y_tr, y_te = y.iloc[tr], y.iloc[te]
        g_te = groups.iloc[te].astype(str)

        le = LabelEncoder()
        y_tr_enc = le.fit_transform(y_tr.astype(str))
        y_te_enc = le.transform(y_te.astype(str))
        sw = _make_sample_weights(y_tr_enc)

        pipe = make_pipe(clone(model))
        pipe.fit(X_tr, y_tr_enc, model__sample_weight=sw)
        pred_enc = pipe.predict(X_te)

        sample_rows.append({
            'fold': fold,
            'accuracy': accuracy_score(y_te_enc, pred_enc),
            'balanced_accuracy': balanced_accuracy_score(y_te_enc, pred_enc),
            'f1_macro': f1_score(y_te_enc, pred_enc, average='macro', zero_division=0),
        })

        # Speaker-level aggregation by averaging class probabilities
        proba = pipe.predict_proba(X_te)
        proba_df = pd.DataFrame(proba, columns=[f'c_{i}' for i in range(proba.shape[1])])
        proba_df['speaker_id'] = g_te.values
        spk_proba = proba_df.groupby('speaker_id', as_index=False).mean()

        spk_pred_enc = spk_proba[[c for c in spk_proba.columns if c.startswith('c_')]].values.argmax(axis=1)
        spk_true = pd.DataFrame({'speaker_id': g_te.values, 'y': y_te.astype(str).values}).groupby('speaker_id')['y'].agg(lambda s: s.mode().iloc[0]).reset_index()
        spk_true_enc = le.transform(spk_true['y'].values)

        speaker_rows.append({
            'fold': fold,
            'accuracy': accuracy_score(spk_true_enc, spk_pred_enc),
            'balanced_accuracy': balanced_accuracy_score(spk_true_enc, spk_pred_enc),
            'f1_macro': f1_score(spk_true_enc, spk_pred_enc, average='macro', zero_division=0),
        })

    sample_df = pd.DataFrame(sample_rows)
    speaker_df = pd.DataFrame(speaker_rows)

    sample_summary = {
        'accuracy_mean': sample_df['accuracy'].mean(),
        'balanced_accuracy_mean': sample_df['balanced_accuracy'].mean(),
        'f1_macro_mean': sample_df['f1_macro'].mean(),
    }
    speaker_summary = {
        'accuracy_mean': speaker_df['accuracy'].mean(),
        'balanced_accuracy_mean': speaker_df['balanced_accuracy'].mean(),
        'f1_macro_mean': speaker_df['f1_macro'].mean(),
    }
    return sample_summary, speaker_summary

In [12]:
# Binary Classification Run
binary_models = {
    'LogReg': LogisticRegression(max_iter=3000, class_weight='balanced', C=1.0, random_state=RANDOM_SEED),
    'RandomForest': RandomForestClassifier(
        n_estimators=800, max_depth=None, min_samples_leaf=2,
        class_weight='balanced_subsample', random_state=RANDOM_SEED, n_jobs=-1
    ),
    'LightGBM': LGBMClassifier(
        n_estimators=800, learning_rate=0.03, num_leaves=63,
        min_child_samples=15, subsample=0.8, colsample_bytree=0.8,
        class_weight='balanced', random_state=RANDOM_SEED, n_jobs=-1, verbose=-1
    ),
    'XGBoost': XGBClassifier(
        n_estimators=700, learning_rate=0.03, max_depth=6,
        subsample=0.8, colsample_bytree=0.8, min_child_weight=3,
        reg_alpha=1.0, reg_lambda=2.0,
        random_state=RANDOM_SEED, n_jobs=-1, eval_metric='logloss'
    ),
}

# Token-level metrics (no K sweep — all features used natively)
bin_rows = []
for model_name, model in binary_models.items():
    fold_df, summ = evaluate_binary_sample_cv(model, X, y_bin, groups, n_splits=N_SPLITS)
    bin_rows.append({'model': model_name, **summ})

bin_results = pd.DataFrame(bin_rows).sort_values(
    by=['accuracy_mean', 'balanced_accuracy_mean'], ascending=False
).reset_index(drop=True)
print('Token-level binary metrics')
display(bin_results)

# Speaker-level metrics (recommended for clinical decision use)
bin_spk_rows = []
for model_name, model in binary_models.items():
    fold_df, summ = evaluate_binary_speaker_cv(model, X, y_bin, groups, n_splits=N_SPLITS)
    bin_spk_rows.append({'model': model_name, **summ})

bin_speaker_results = pd.DataFrame(bin_spk_rows).sort_values(
    by=['accuracy_mean', 'balanced_accuracy_mean'], ascending=False
).reset_index(drop=True)
print('Speaker-level binary metrics (speaker-aggregated probabilities)')
display(bin_speaker_results)

Token-level binary metrics

          model  accuracy_mean  balanced_accuracy_mean  f1_macro_mean
0      LightGBM       0.772990                0.777013       0.769938
1        LogReg       0.770530                0.770932       0.766311
2       XGBoost       0.768046                0.776300       0.766172
3  RandomForest       0.754482                0.757755       0.750842

Speaker-level binary metrics (speaker-aggregated probabilities)

          model  accuracy_mean  balanced_accuracy_mean  f1_macro_mean
0      LightGBM       0.751341                0.751776       0.750626
1        LogReg       0.749066                0.749288       0.748575
2       XGBoost       0.747671                0.748320       0.746239
3  RandomForest       0.736374                0.736888       0.735634

In [13]:
# Multi-Class Run (Pathological Only)
idx_patho = y_bin == 0
X_patho, y_patho, g_patho = X[idx_patho], y_multi[idx_patho], groups[idx_patho]

multi_models = {
    'RandomForest': RandomForestClassifier(n_estimators=300, max_depth=10, class_weight='balanced_subsample', random_state=RANDOM_SEED, n_jobs=-1),
    'LightGBM': LGBMClassifier(n_estimators=300, learning_rate=0.05, class_weight='balanced', random_state=RANDOM_SEED, n_jobs=-1, verbose=-1),
    'XGBoost': XGBClassifier(
        n_estimators=400, learning_rate=0.05, max_depth=5,
        subsample=0.8, colsample_bytree=0.8, min_child_weight=3,
        reg_alpha=1.0, reg_lambda=2.0,
        random_state=RANDOM_SEED, n_jobs=-1, eval_metric='mlogloss'
    ),
}

# Run baseline models (no K sweep — all features used natively)
multi_sample_rows, multi_speaker_rows = [], []
for model_name, model in multi_models.items():
    ssum, spksum = evaluate_multiclass_sample_and_speaker_cv(model, X_patho, y_patho, g_patho, n_splits=N_SPLITS)
    multi_sample_rows.append({'model': model_name, **ssum})
    multi_speaker_rows.append({'model': model_name, **spksum})

multi_results = pd.DataFrame(multi_sample_rows).sort_values(
    by=['accuracy_mean', 'balanced_accuracy_mean'], ascending=False
).reset_index(drop=True)
print('Token-level multi-class metrics')
display(multi_results)

multi_speaker_results = pd.DataFrame(multi_speaker_rows).sort_values(
    by=['accuracy_mean', 'balanced_accuracy_mean'], ascending=False
).reset_index(drop=True)
print('Speaker-level multi-class metrics (speaker-aggregated probabilities)')
display(multi_speaker_results)

Token-level multi-class metrics

          model  accuracy_mean  balanced_accuracy_mean  f1_macro_mean
0       XGBoost       0.529363                0.510268       0.510439
1      LightGBM       0.515773                0.495972       0.497831
2  RandomForest       0.512676                0.486348       0.485787

Speaker-level multi-class metrics (speaker-aggregated probabilities)

          model  accuracy_mean  balanced_accuracy_mean  f1_macro_mean
0       XGBoost       0.527945                0.497927        0.49303
1  RandomForest       0.512225                0.470235        0.46927
2      LightGBM       0.510318                0.485412        0.48244